---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Sname }}
spec:
  type: {{ .Values.SType }}
  selector:
    app: {{ .Values.app }}
    ENV: {{ .Values.ENV }}
  ports:
    - port: {{ .Values.SPort }}
      targetPort: {{ .Values.containerPort }}